baseURL = 'https://mackenziebasaraba.ca/'
languageCode = 'en-ca'
title = 'MacKenzie-Basaraba'


[params]
    incomingpages = "Incoming pages:"
    outgoing = "Outgoing pages:"
    sitetitle = "pmb"

enableGitInfo = true
[frontmatter]
    lastmod = ["lastmod", ":fileModTime", ":git", "publishDate"]

[params.author]
    name = 'Peter MacKenzie-Basaraba'
    email = 'peter@mackenziebasaraba.ca'
